### ISSUE TITLE
Support microsoft bot emulator

### ISSUE THREAD

**Issue by tachyons** [tachyons/botframework-ruby#5]

**Comment by 7sedam7** [comment]
Hello, 

I installed the gem and bot framework emulator and tried to use echo bot with no success.

emulator: `Request to 'http://localhost:9292' failed: [500] Internal Server Error`

rack: 
```
...
OAuth2::Error:
	/Users/joelmislavkunst/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/oauth2-1.3.1/lib/oauth2/client.rb:119:in `request'
...
```

**Comment by tachyons** [comment]
Can you please provide full stack trace of the error. Also try by commenting the line 
```ruby
conversation_data(activity)
```

**Comment by tachyons** [comment]
Also check if the issue is https://github.com/tachyons/botframework-ruby/issues/22 . This fix is still in master, not in released version

**Comment by 7sedam7** [comment]
after commenting out the `conversation_data(activity)` it worked, thanks :)

**Comment by tachyons** [comment]
Welcome
